[2023-10-03T09:40:18.700+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: capstone_project.check_results scheduled__2023-09-29T00:00:00+00:00 [queued]>
[2023-10-03T09:40:18.810+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: capstone_project.check_results scheduled__2023-09-29T00:00:00+00:00 [queued]>
[2023-10-03T09:40:18.814+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2023-10-03T09:40:18.929+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): check_results> on 2023-09-29 00:00:00+00:00
[2023-10-03T09:40:18.961+0000] {standard_task_runner.py:57} INFO - Started process 1212 to run task
[2023-10-03T09:40:18.970+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'capstone_project', 'check_results', 'scheduled__2023-09-29T00:00:00+00:00', '--job-id', '131', '--raw', '--subdir', 'DAGS_FOLDER/capstone_project.py', '--cfg-path', '/tmp/tmpyotzekst']
[2023-10-03T09:40:19.006+0000] {standard_task_runner.py:85} INFO - Job 131: Subtask check_results
[2023-10-03T09:40:19.194+0000] {task_command.py:410} INFO - Running <TaskInstance: capstone_project.check_results scheduled__2023-09-29T00:00:00+00:00 [running]> on host 9a30478b5169
[2023-10-03T09:40:19.636+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='capstone_project' AIRFLOW_CTX_TASK_ID='check_results' AIRFLOW_CTX_EXECUTION_DATE='2023-09-29T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-09-29T00:00:00+00:00'
[2023-10-03T09:40:19.682+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/capstone_project.py", line 39, in _check_if_data_in_request
    response_dict = json.loads(response)
  File "/usr/local/lib/python3.7/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType
[2023-10-03T09:40:19.693+0000] {taskinstance.py:1373} INFO - Marking task as FAILED. dag_id=capstone_project, task_id=check_results, execution_date=20230929T000000, start_date=20231003T094018, end_date=20231003T094019
[2023-10-03T09:40:19.713+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 131 for task check_results (the JSON object must be str, bytes or bytearray, not NoneType; 1212)
[2023-10-03T09:40:19.756+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-10-03T09:40:19.811+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-10-03T12:57:42.119+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: capstone_project.check_results scheduled__2023-09-29T00:00:00+00:00 [queued]>
[2023-10-03T12:57:42.193+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: capstone_project.check_results scheduled__2023-09-29T00:00:00+00:00 [queued]>
[2023-10-03T12:57:42.194+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2023-10-03T12:57:42.371+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): check_results> on 2023-09-29 00:00:00+00:00
[2023-10-03T12:57:42.444+0000] {standard_task_runner.py:57} INFO - Started process 191 to run task
[2023-10-03T12:57:42.499+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'capstone_project', 'check_results', 'scheduled__2023-09-29T00:00:00+00:00', '--job-id', '316', '--raw', '--subdir', 'DAGS_FOLDER/capstone_project.py', '--cfg-path', '/tmp/tmp686qb5ta']
[2023-10-03T12:57:42.517+0000] {standard_task_runner.py:85} INFO - Job 316: Subtask check_results
[2023-10-03T12:57:42.844+0000] {task_command.py:410} INFO - Running <TaskInstance: capstone_project.check_results scheduled__2023-09-29T00:00:00+00:00 [running]> on host 9a30478b5169
[2023-10-03T12:57:43.351+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='capstone_project' AIRFLOW_CTX_TASK_ID='check_results' AIRFLOW_CTX_EXECUTION_DATE='2023-09-29T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-09-29T00:00:00+00:00'
[2023-10-03T12:57:43.400+0000] {logging_mixin.py:149} INFO - {"count":0,"next":null,"previous":null,"results":[]} <class 'str'>
[2023-10-03T12:57:43.400+0000] {taskinstance.py:1454} INFO - No launches for today 2023-09-29.
[2023-10-03T12:57:43.424+0000] {taskinstance.py:1373} INFO - Marking task as SKIPPED. dag_id=capstone_project, task_id=check_results, execution_date=20230929T000000, start_date=20231003T125742, end_date=20231003T125743
[2023-10-03T12:57:43.505+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 0
[2023-10-03T12:57:43.600+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
